// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tables": {
            "get": {
                "description": "Lista as mesas. Sem o parâmetro ` + "`" + `active` + "`" + `, devolve todas — ativas e inativas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mesas"
                ],
                "summary": "Lista mesas",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Filtra por mesas ativas (true) ou inativas (false). Omitido = sem filtro",
                        "name": "active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/table.Table"
                            }
                        }
                    },
                    "400": {
                        "description": "Parâmetro active não é booleano",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Cadastra uma mesa nova. O nome é único no restaurante.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mesas"
                ],
                "summary": "Cria uma mesa",
                "parameters": [
                    {
                        "description": "Dados da mesa",
                        "name": "mesa",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/table.createRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/table.Table"
                        }
                    },
                    "400": {
                        "description": "Corpo inválido, nome vazio ou capacidade fora do intervalo",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Já existe mesa com esse nome",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tables/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mesas"
                ],
                "summary": "Detalha uma mesa",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da mesa (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/table.Table"
                        }
                    },
                    "400": {
                        "description": "ID não é um UUID",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mesa não encontrada",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Atualização parcial: só os campos enviados são alterados. Enviar ` + "`" + `{\"is_active\": false}` + "`" + ` desativa a mesa.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mesas"
                ],
                "summary": "Atualiza uma mesa",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da mesa (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos a alterar (ao menos um)",
                        "name": "mesa",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/table.updateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/table.Table"
                        }
                    },
                    "400": {
                        "description": "Corpo vazio, ID inválido ou valor fora do intervalo",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mesa não encontrada",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Já existe mesa com o novo nome",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpx.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Grupo de 6 pessoas excede a capacidade da mesa (4)."
                }
            }
        },
        "table.Table": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "table.createRequest": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer",
                    "example": 4
                },
                "name": {
                    "type": "string",
                    "example": "Mesa 12"
                }
            }
        },
        "table.updateRequest": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer",
                    "example": 6
                },
                "is_active": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "Mesa 12"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Reservas de Restaurante",
	Description:      "Backend de reservas de mesas de um restaurante único. Staff cria reservas; o sistema aloca mesa automaticamente respeitando capacidade e evitando sobreposição de horário.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
